create schema qnda;

-- Table: qnda.tb_course

-- DROP TABLE qnda.tb_course;

CREATE TABLE qnda.tb_course
(
    course_id bigint  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL,
    course_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by character varying(255) COLLATE pg_catalog."default" ,
    modified_at timestamp without time zone,

    CONSTRAINT tb_course_pkey PRIMARY KEY (course_id)
);

-- Table: qnda.chapters

-- DROP TABLE qnda.chapters;

CREATE TABLE qnda.tb_chapters
(
    chapter_id bigint  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL,
    course_id bigint REFERENCES qnda.tb_course(course_id) NOT NULL,
    chapter_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by character varying(255) COLLATE pg_catalog."default" ,
    modified_at timestamp without time zone,

    CONSTRAINT tb_chapters_pkey PRIMARY KEY (chapter_id)
);


-- Table: qnda.topics

-- DROP TABLE qnda.topics;

CREATE TABLE qnda.tb_topics
(
    topic_id bigint  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL,
    chapter_id bigint REFERENCES qnda.tb_chapters(chapter_id) NOT NULL,
    topic_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by character varying(255) COLLATE pg_catalog."default" ,
    modified_at timestamp without time zone,

    CONSTRAINT tb_topics_pkey PRIMARY KEY (topic_id)
)

CREATE TABLE qnda.tb_questions
(
    question_id bigint  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000) NOT NULL,
    topic_id bigint REFERENCES qnda.tb_topics(topic_id) NOT NULL,
    question character varying(255) COLLATE pg_catalog."default" NOT NULL,
    answer text COLLATE pg_catalog."default",
    difficulty_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_public boolean NOT NULL,
    is_active boolean NOT NULL,
    created_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by character varying(255) COLLATE pg_catalog."default" ,
    modified_at timestamp without time zone,

    CONSTRAINT question_id_pkey PRIMARY KEY (question_id)
)

